version: '3.0'
services:
    typecho:
        image: 80x86/typecho:latest
        container_name: VRC_Blog
        volumes:
            - ./data:/data
        ports:
            - 8001:80
        restart: always
        environment:
            PHP_TZ: Asia/Shanghai
            PHP_MAX_EXECUTION_TIME: 600
